//
//  Images.swift
//  Native
//

import Foundation

struct Images {
    
    // MARK: - Properties:
    
    /// Images that are used in the onboarding screens:
    static let onboarding21: String = "Onboarding-2-1"
    static let onboarding22: String = "Onboarding-2-2"
    static let onboarding23: String = "Onboarding-2-3"
    static let onboarding4: String = "Onboarding-4"
    static let onboarding61: String = "Onboarding-6-1"
    static let onboarding62: String = "Onboarding-6-2"
    static let onboarding63: String = "Onboarding-6-3"
    static let onboarding64: String = "Onboarding-6-4"
    static let onboarding7: String = "Onboarding-7"
    static let onboarding81: String = "Onboarding-8-1"
    static let onboarding82: String = "Onboarding-8-2"
    static let onboarding83: String = "Onboarding-8-3"
    static let onboarding9: String = "Onboarding-9"
    static let onboarding10: String = "Onboarding-10"
    static let onboarding121: String = "Onboarding-12-1"
    static let onboarding122: String = "Onboarding-12-2"
    static let onboarding123: String = "Onboarding-12-3"
    static let onboarding131: String = "Onboarding-13-1"
    static let onboarding132: String = "Onboarding-13-2"
    static let onboarding14: String = "Onboarding-14"
    static let onboarding151: String = "Onboarding-15-1"
    static let onboarding152: String = "Onboarding-15-2"
    static let onboarding153: String = "Onboarding-15-3"
    static let onboarding154: String = "Onboarding-15-4"
    
    /// Images that are used in the login screens:
    static let login4: String = "Login-4"
    
    /// Images that are used in the password reset screens:
    static let passwordReset3: String = "Password-Reset-3"
    
    /// Images that are used in the paywall screens:
    static let paywall31: String = "Paywall-3-1"
    static let paywall32: String = "Paywall-3-2"
    static let paywall33: String = "Paywall-3-3"
    static let paywall4: String = "Paywall-4"
    static let paywall5: String = "Paywall-5"
    static let paywall7: String = "Paywall-7"
    static let paywall81: String = "Paywall-8-1"
    static let paywall82: String = "Paywall-8-2"
    static let paywall83: String = "Paywall-8-3"
    static let paywall101: String = "Paywall-10-1"
    static let paywall102: String = "Paywall-10-2"
    static let paywall103: String = "Paywall-10-3"
    static let paywall111: String = "Paywall-11-1"
    static let paywall112: String = "Paywall-11-2"
    static let paywall113: String = "Paywall-11-3"
    static let paywall114: String = "Paywall-11-4"
    static let paywall121: String = "Paywall-12-1"
    static let paywall122: String = "Paywall-12-2"
    static let paywall123: String = "Paywall-12-3"
    static let paywall131: String = "Paywall-13-1"
    static let paywall132: String = "Paywall-13-2"
    static let paywall133: String = "Paywall-13-3"
    static let paywall134: String = "Paywall-13-4"
    static let paywall14: String = "Paywall-14"
    static let paywall15: String = "Paywall-15"
    
    /// Images that are used in the empty state screens:
    static let emptyState3: String = "Empty-State-3"
    
    /// Images that are used in the main screens:
    static let main21: String = "Main-2-1"
    static let main22: String = "Main-2-2"
    static let main23: String = "Main-2-3"
    static let main24: String = "Main-2-4"
    static let main25: String = "Main-2-5"
    static let main26: String = "Main-2-6"
    static let main27: String = "Main-2-7"
    static let main28: String = "Main-2-8"
    static let main31: String = "Main-3-1"
    static let main32: String = "Main-3-2"
    static let main33: String = "Main-3-3"
    static let main34: String = "Main-3-4"
    static let main35: String = "Main-3-5"
    static let main41: String = "Main-4-1"
    static let main42: String = "Main-4-2"
    static let main43: String = "Main-4-3"
    static let main51: String = "Main-5-1"
    static let main52: String = "Main-5-2"
    static let main53: String = "Main-5-3"
    static let main61: String = "Main-6-1"
    static let main62: String = "Main-6-2"
    static let main63: String = "Main-6-3"
    static let main64: String = "Main-6-4"
    static let main65: String = "Main-6-5"
    static let main66: String = "Main-6-6"
    static let main67: String = "Main-6-7"
    static let main68: String = "Main-6-8"
    static let main69: String = "Main-6-9"
    static let main610: String = "Main-6-10"
    static let main81: String = "Main-8-1"
    static let main82: String = "Main-8-2"
    static let main83: String = "Main-8-3"
    static let main84: String = "Main-8-4"
    static let main85: String = "Main-8-5"
    static let main86: String = "Main-8-6"
    static let main87: String = "Main-8-7"
    static let main88: String = "Main-8-8"
    static let main89: String = "Main-8-9"
    static let main810: String = "Main-8-10"
    static let main811: String = "Main-8-11"
    static let main812: String = "Main-8-12"
    static let main813: String = "Main-8-13"
    static let main814: String = "Main-8-14"
    static let main815: String = "Main-8-15"
    static let main816: String = "Main-8-16"
    static let main817: String = "Main-8-17"
    static let main818: String = "Main-8-18"
    static let main819: String = "Main-8-19"
    static let main820: String = "Main-8-20"
    
    /// Images that are used in the product details screens:
    static let productDetails1: String = "Product-Details-1"
    static let productDetails2: String = "Product-Details-2"
    static let productDetails3: String = "Product-Details-3"
    static let productDetails4: String = "Product-Details-4"
    static let productDetails5: String = "Product-Details-5"
    static let productDetails6: String = "Product-Details-6"
    static let productDetails7: String = "Product-Details-7"
    static let productDetails8: String = "Product-Details-8"
    static let productDetails9: String = "Product-Details-9"
    static let productDetails10: String = "Product-Details-10"
    static let productDetails11: String = "Product-Details-11"
    static let productDetails12: String = "Product-Details-12"
    static let productDetails13: String = "Product-Details-13"
    static let productDetails14: String = "Product-Details-14"
    static let productDetails15: String = "Product-Details-15"
    
    /// Images that are used in the file editing screens:
    static let fileEditing11: String = "File-Editing-1-1"
    static let fileEditing12: String = "File-Editing-1-2"
    static let fileEditing13: String = "File-Editing-1-3"
    static let fileEditing14: String = "File-Editing-1-4"
    static let fileEditing15: String = "File-Editing-1-5"
    static let fileEditing16: String = "File-Editing-1-6"
    static let fileEditing17: String = "File-Editing-1-7"
    static let fileEditing18: String = "File-Editing-1-8"
    static let fileEditing19: String = "File-Editing-1-9"
    static let fileEditing110: String = "File-Editing-1-10"
    static let fileEditing21: String = "File-Editing-2-1"
    static let fileEditing22: String = "File-Editing-2-2"
    static let fileEditing23: String = "File-Editing-2-3"
    static let fileEditing24: String = "File-Editing-2-4"
    static let fileEditing25: String = "File-Editing-2-5"
    static let fileEditing26: String = "File-Editing-2-6"
    static let fileEditing27: String = "File-Editing-2-7"
    static let fileEditing28: String = "File-Editing-2-8"
    static let fileEditing5: String = "File-Editing-5"
    
    /// Images that are used in the profile screens:
    static let profile1: String = "Profile-1"
    static let profile21: String = "Profile-2-1"
    static let profile22: String = "Profile-2-2"
    static let profile23: String = "Profile-2-3"
    static let profile24: String = "Profile-2-4"
    static let profile25: String = "Profile-2-5"
    static let profile26: String = "Profile-2-6"
    static let profile27: String = "Profile-2-7"
    static let profile28: String = "Profile-2-8"
    static let profile29: String = "Profile-2-9"
    static let profile210: String = "Profile-2-10"
    static let profile3: String = "Profile-3"
    static let profile4: String = "Profile-4"
    static let profile51: String = "Profile-5-1"
    static let profile52: String = "Profile-5-2"
    static let profile53: String = "Profile-5-3"
    static let profile54: String = "Profile-5-4"
    static let profile55: String = "Profile-5-5"
    static let profile56: String = "Profile-5-6"
    
    /// Images that are used in the account screens:
    static let account1: String = "Account-1"
    static let account2: String = "Account-2"
    static let account3: String = "Account-3"
    static let account4: String = "Account-4"
    static let account5: String = "Account-5"
}
